// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result } from "dedot/codecs";
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from "dedot/contracts";
import type { InkPrimitivesLangError } from "./types.js";

export interface ConstructorQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericConstructorQuery<ChainApi, Type> {
  /**
   * Constructor that initializes the staking contract
   *
   * @param {H160} w3piToken
   * @param {H160} registry
   * @param {H160} feeWallet
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      w3piToken: H160,
      registry: H160,
      feeWallet: H160,
      options?: ConstructorCallOptions,
    ) => Promise<
      GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>
    >,
    Type
  >;
}
