// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<ChainApi, Type> {
  /**
   * Constructor that initializes the staking contract
   *
   * @param {H160} w3piToken
   * @param {H160} registry
   * @param {H160} feeWallet
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      w3piToken: H160,
      registry: H160,
      feeWallet: H160,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;
}
