// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   * Event emitted when tokens are staked
   *
   *
   **/
  Staked: GenericContractEvent<
    "Staked",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      unstakingPeriod: bigint;
    },
    Type
  >;

  /**
   * Event emitted when an unstaking request is created
   *
   *
   **/
  UnstakeRequested: GenericContractEvent<
    "UnstakeRequested",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      availableAt: bigint;
    },
    Type
  >;

  /**
   * Event emitted when unstaked tokens are claimed
   *
   *
   **/
  UnstakedClaimed: GenericContractEvent<
    "UnstakedClaimed",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Event emitted when rewards are claimed
   *
   *
   **/
  RewardsClaimed: GenericContractEvent<
    "RewardsClaimed",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Event emitted when the contract is paused
   *
   *
   **/
  ContractPaused: GenericContractEvent<
    "ContractPaused",
    {
      /**
       *
       * @indexed: true
       **/
      by: AccountId32;
    },
    Type
  >;

  /**
   * Event emitted when the contract is unpaused
   *
   *
   **/
  ContractUnpaused: GenericContractEvent<
    "ContractUnpaused",
    {
      /**
       *
       * @indexed: true
       **/
      by: AccountId32;
    },
    Type
  >;

  /**
   * Event emitted when performance fees are claimed
   *
   *
   **/
  PerformanceFeeClaimed: GenericContractEvent<
    "PerformanceFeeClaimed",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      feeAmount: bigint;
    },
    Type
  >;
}
