// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";
import type { SharedTier } from "./types.js";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   * Event emitted when an obsolete stake is reallocated
   *
   *
   **/
  ObsoleteStakeReallocated: GenericContractEvent<
    "ObsoleteStakeReallocated",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: true
       **/
      obsoleteToken: AccountId32;
      /**
       *
       * @indexed: false
       **/
      stakeAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      usdcValue: bigint;
      /**
       *
       * @indexed: false
       **/
      redistributedToTokens: number;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   * Event emitted when tokens are staked
   *
   *
   **/
  Staked: GenericContractEvent<
    "Staked",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      unstakingPeriod: bigint;
    },
    Type
  >;

  /**
   * Event emitted when the contract is paused
   *
   *
   **/
  ContractPaused: GenericContractEvent<
    "ContractPaused",
    {
      /**
       *
       * @indexed: true
       **/
      by: AccountId32;
    },
    Type
  >;

  /**
   * Event emitted when rewards are claimed
   *
   *
   **/
  RewardsClaimed: GenericContractEvent<
    "RewardsClaimed",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Event emitted when unstaked tokens are claimed
   *
   *
   **/
  UnstakedClaimed: GenericContractEvent<
    "UnstakedClaimed",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Event emitted when the contract is unpaused
   *
   *
   **/
  ContractUnpaused: GenericContractEvent<
    "ContractUnpaused",
    {
      /**
       *
       * @indexed: true
       **/
      by: AccountId32;
    },
    Type
  >;

  /**
   * Event emitted when an unstaking request is created
   *
   *
   **/
  UnstakeRequested: GenericContractEvent<
    "UnstakeRequested",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      availableAt: bigint;
    },
    Type
  >;

  /**
   * Event emitted when rewards pool is funded
   *
   *
   **/
  RewardsPoolFunded: GenericContractEvent<
    "RewardsPoolFunded",
    {
      /**
       *
       * @indexed: true
       **/
      funder: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      newBalance: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   * Event emitted when tier change is received from Registry
   *
   *
   **/
  TierChangeReceived: GenericContractEvent<
    "TierChangeReceived",
    {
      /**
       *
       * @indexed: false
       **/
      oldTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      newTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   * Event emitted when obsolete stakes are detected
   *
   *
   **/
  ZombieStakesDetected: GenericContractEvent<
    "ZombieStakesDetected",
    {
      /**
       *
       * @indexed: false
       **/
      totalZombieStakes: number;
      /**
       *
       * @indexed: false
       **/
      totalZombieValue: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   * Event emitted when mass unstaking is detected and contract is auto-paused
   *
   *
   **/
  MassUnstakingDetected: GenericContractEvent<
    "MassUnstakingDetected",
    {
      /**
       *
       * @indexed: true
       **/
      triggeredBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      unstakingVolume: bigint;
      /**
       *
       * @indexed: false
       **/
      threshold: bigint;
      /**
       *
       * @indexed: false
       **/
      totalStaked: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   * Event emitted when performance fees are claimed
   *
   *
   **/
  PerformanceFeeClaimed: GenericContractEvent<
    "PerformanceFeeClaimed",
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      feeAmount: bigint;
    },
    Type
  >;

  /**
   * Event emitted when zombie cleanup is completed
   *
   *
   **/
  ZombieCleanupCompleted: GenericContractEvent<
    "ZombieCleanupCompleted",
    {
      /**
       *
       * @indexed: false
       **/
      stakesProcessed: number;
      /**
       *
       * @indexed: false
       **/
      totalValueReallocated: bigint;
      /**
       *
       * @indexed: false
       **/
      tokensRedistributed: number;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;
}
