// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Result, H160 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type {
  SharedError,
  InkPrimitivesLangError,
  StakingStakeInfo,
  StakingUnstakingRequest,
} from "./types.js";

export interface ContractQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractQuery<ChainApi, Type> {
  /**
   * Stake W3PI tokens
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x5adb38de
   **/
  stake: GenericContractQueryCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Request to unstake tokens
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xfd83c46b
   **/
  requestUnstake: GenericContractQueryCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Claim unstaked tokens that have completed the unstaking period
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x67c2988d
   **/
  claimUnstaked: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Claim staking rewards without unstaking
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8027650c
   **/
  claimRewards: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * View function to get claimable rewards
   *
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x2015e04b
   **/
  getClaimableRewards: GenericContractQueryCall<
    ChainApi,
    (
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xe2597c6d
   **/
  getTotalCollectedFees: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   *
   * @param {H160} newFeeWallet
   * @param {ContractCallOptions} options
   *
   * @selector 0x3a3baac1
   **/
  setFeeWallet: GenericContractQueryCall<
    ChainApi,
    (
      newFeeWallet: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * View function to get account stake info
   *
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x19617e8c
   **/
  getStakeInfo: GenericContractQueryCall<
    ChainApi,
    (
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        StakingStakeInfo | undefined,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * View function to get unstaking requests
   *
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x01777c09
   **/
  getUnstakingRequests: GenericContractQueryCall<
    ChainApi,
    (
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<StakingUnstakingRequest>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * View function to get total staked amount
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x02c779a5
   **/
  getTotalStaked: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Pause the contract (owner only)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x81e0c604
   **/
  pause: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Unpause the contract (owner only)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x67616649
   **/
  unpause: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Update the W3PI token address (owner only)
   *
   * @param {H160} newToken
   * @param {ContractCallOptions} options
   *
   * @selector 0x1ca306e1
   **/
  setW3piToken: GenericContractQueryCall<
    ChainApi,
    (
      newToken: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Update the registry address (owner only)
   *
   * @param {H160} newRegistry
   * @param {ContractCallOptions} options
   *
   * @selector 0xa55c4b84
   **/
  setRegistry: GenericContractQueryCall<
    ChainApi,
    (
      newRegistry: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;
}
