// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Stake W3PI tokens
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x5adb38de
   **/
  stake: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Request to unstake tokens
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xfd83c46b
   **/
  requestUnstake: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Claim unstaked tokens that have completed the unstaking period
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x67c2988d
   **/
  claimUnstaked: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Claim staking rewards without unstaking
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x8027650c
   **/
  claimRewards: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {H160} newFeeWallet
   * @param {ContractTxOptions} options
   *
   * @selector 0x3a3baac1
   **/
  setFeeWallet: GenericContractTxCall<
    ChainApi,
    (
      newFeeWallet: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Pause the contract (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x81e0c604
   **/
  pause: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Unpause the contract (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x67616649
   **/
  unpause: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update the W3PI token address (owner only)
   *
   * @param {H160} newToken
   * @param {ContractTxOptions} options
   *
   * @selector 0x1ca306e1
   **/
  setW3piToken: GenericContractTxCall<
    ChainApi,
    (
      newToken: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update the registry address (owner only)
   *
   * @param {H160} newRegistry
   * @param {ContractTxOptions} options
   *
   * @selector 0xa55c4b84
   **/
  setRegistry: GenericContractTxCall<
    ChainApi,
    (
      newRegistry: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
