// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";
import type { SharedTier } from "./types.js";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Stake W3PI tokens
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x5adb38de
   **/
  stake: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Request to unstake tokens
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xfd83c46b
   **/
  requestUnstake: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Claim unstaked tokens that have completed the unstaking period
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x67c2988d
   **/
  claimUnstaked: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Claim staking rewards without unstaking
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x8027650c
   **/
  claimRewards: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {H160} newFeeWallet
   * @param {ContractTxOptions} options
   *
   * @selector 0x3a3baac1
   **/
  setFeeWallet: GenericContractTxCall<
    ChainApi,
    (
      newFeeWallet: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Pause the contract (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x81e0c604
   **/
  pause: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Unpause the contract (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x67616649
   **/
  unpause: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update the W3PI token address (owner only)
   *
   * @param {H160} newToken
   * @param {ContractTxOptions} options
   *
   * @selector 0x1ca306e1
   **/
  setW3piToken: GenericContractTxCall<
    ChainApi,
    (
      newToken: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update the registry address (owner only)
   *
   * @param {H160} newRegistry
   * @param {ContractTxOptions} options
   *
   * @selector 0xa55c4b84
   **/
  setRegistry: GenericContractTxCall<
    ChainApi,
    (
      newRegistry: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set portfolio contract (owner only)
   *
   * @param {H160} portfolio
   * @param {ContractTxOptions} options
   *
   * @selector 0x35760b89
   **/
  setPortfolioContract: GenericContractTxCall<
    ChainApi,
    (
      portfolio: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set DEX contract (owner only)
   *
   * @param {H160} dex
   * @param {ContractTxOptions} options
   *
   * @selector 0xb53ae601
   **/
  setDexContract: GenericContractTxCall<
    ChainApi,
    (
      dex: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set USDC contract (owner only)
   *
   * @param {H160} usdc
   * @param {ContractTxOptions} options
   *
   * @selector 0x46e77b11
   **/
  setUsdcContract: GenericContractTxCall<
    ChainApi,
    (
      usdc: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Cleanup zombie stakes - auto unstake obsolete positions
   * This should be called during monthly rebalancing
   * Flow: Remove stake → Swap W3PI to USDC via DEX → Transfer USDC to Portfolio → Portfolio redistributes
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x32efb9ca
   **/
  cleanupZombieStakes: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Force unstake an obsolete position for a specific account (owner only)
   *
   * @param {H160} account
   * @param {ContractTxOptions} options
   *
   * @selector 0xb9541bf0
   **/
  forceUnstakeObsolete: GenericContractTxCall<
    ChainApi,
    (
      account: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Reset unstaking detection period (owner only - emergency use)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x731722fc
   **/
  resetUnstakingDetection: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set zombie cleanup interval (owner only)
   *
   * @param {bigint} interval
   * @param {ContractTxOptions} options
   *
   * @selector 0xcf3759d6
   **/
  setZombieCleanupInterval: GenericContractTxCall<
    ChainApi,
    (
      interval: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Handle tier change notification from Registry
   * This updates unstaking periods for existing stakes
   *
   * @param {SharedTier} oldTier
   * @param {SharedTier} newTier
   * @param {ContractTxOptions} options
   *
   * @selector 0xa5982f5f
   **/
  onTierChange: GenericContractTxCall<
    ChainApi,
    (
      oldTier: SharedTier,
      newTier: SharedTier,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Fund the rewards pool with W3PI tokens (owner or authorized)
   * Requires prior approval of tokens to this contract
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xbd39b69c
   **/
  fundRewardsPool: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Withdraw excess rewards from pool (owner only, for emergency)
   *
   * @param {bigint} amount
   * @param {H160} to
   * @param {ContractTxOptions} options
   *
   * @selector 0x3dbc47f0
   **/
  withdrawRewardsPool: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      to: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
