// Generated by dedot cli

import type { H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type StakingStakeInfo = {
  amount: bigint;
  stakedAt: bigint;
  lastClaim: bigint;
  unstakingPeriod: bigint;
  tierAtStake: SharedTier;
};

export type SharedTier = "None" | "Tier1" | "Tier2" | "Tier3" | "Tier4";

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type StakingUnstakingRequest = {
  amount: bigint;
  requestedAt: bigint;
  availableAt: bigint;
  claimed: boolean;
};

export type StakingW3piStaking = {
  w3piToken: H160;
  registry: H160;
  owner: H160;
  paused: boolean;
  stakes: { get(arg: H160): Promise<StakingStakeInfo | undefined> };
  totalStaked: bigint;
  unstakingRequests: {
    get(arg: H160): Promise<Array<StakingUnstakingRequest> | undefined>;
  };
  reentrancyGuard: SharedUtilsReentrancyGuard;
  feeWallet: H160;
  totalCollectedFees: bigint;
  portfolioContract?: H160 | undefined;
  dexContract?: H160 | undefined;
  usdcContract?: H160 | undefined;
  stakerAddresses: Array<H160>;
  lastZombieCleanup: bigint;
  zombieCleanupInterval: bigint;
  rewardsPoolBalance: bigint;
  totalRewardsDistributed: bigint;
  unstakingVolumeCurrentPeriod: bigint;
  unstakingPeriodStart: bigint;
  unstakingPeriodDuration: bigint;
};

export type SharedUtilsReentrancyGuard = { executing: boolean };

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance"
  | "ContractPaused"
  | "CrossContractCallFailed"
  | "TransferFailed"
  | "InvalidParameters";

export type StakingCleanupResult = {
  stakesProcessed: number;
  totalValueReallocated: bigint;
  tokensRedistributed: number;
};
