// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";
import type {
  PortfolioPortfolioState,
  PortfolioFeeConfiguration,
} from "./types.js";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   *
   *
   **/
  PortfolioStateChanged: GenericContractEvent<
    "PortfolioStateChanged",
    {
      /**
       *
       * @indexed: false
       **/
      oldState: PortfolioPortfolioState;
      /**
       *
       * @indexed: false
       **/
      newState: PortfolioPortfolioState;
      /**
       *
       * @indexed: false
       **/
      changedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      reason: string;
    },
    Type
  >;

  /**
   *
   *
   **/
  PortfolioInitialized: GenericContractEvent<
    "PortfolioInitialized",
    {
      /**
       *
       * @indexed: false
       **/
      owner: AccountId32;
      /**
       *
       * @indexed: false
       **/
      deploymentTimestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      indexBaseValue: bigint;
      /**
       *
       * @indexed: false
       **/
      initialState: PortfolioPortfolioState;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenHoldingAdded: GenericContractEvent<
    "TokenHoldingAdded",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      targetWeightBp: number;
      /**
       *
       * @indexed: false
       **/
      addedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenHoldingUpdated: GenericContractEvent<
    "TokenHoldingUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      oldAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      newAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      oldWeight: number;
      /**
       *
       * @indexed: false
       **/
      newWeight: number;
      /**
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenHoldingRemoved: GenericContractEvent<
    "TokenHoldingRemoved",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      finalAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      removedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  IndexValueUpdated: GenericContractEvent<
    "IndexValueUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      oldValue: bigint;
      /**
       *
       * @indexed: false
       **/
      newValue: bigint;
      /**
       *
       * @indexed: false
       **/
      performanceBp: number;
      /**
       *
       * @indexed: false
       **/
      totalPortfolioValue: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  BasePortfolioValueSet: GenericContractEvent<
    "BasePortfolioValueSet",
    {
      /**
       *
       * @indexed: false
       **/
      baseValue: bigint;
      /**
       *
       * @indexed: false
       **/
      basePortfolioValue: bigint;
      /**
       *
       * @indexed: false
       **/
      deploymentTimestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      setBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  FeeConfigurationUpdated: GenericContractEvent<
    "FeeConfigurationUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      oldConfig: PortfolioFeeConfiguration;
      /**
       *
       * @indexed: false
       **/
      newConfig: PortfolioFeeConfiguration;
      /**
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  ContractReferenceUpdated: GenericContractEvent<
    "ContractReferenceUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      contractType: string;
      /**
       *
       * @indexed: false
       **/
      oldAddress: AccountId32 | undefined;
      /**
       *
       * @indexed: false
       **/
      newAddress: AccountId32;
      /**
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  EmergencyPause: GenericContractEvent<
    "EmergencyPause",
    {
      /**
       *
       * @indexed: false
       **/
      paused: boolean;
      /**
       *
       * @indexed: false
       **/
      pausedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      reason: string;
    },
    Type
  >;

  /**
   *
   *
   **/
  OperationFailed: GenericContractEvent<
    "OperationFailed",
    {
      /**
       *
       * @indexed: false
       **/
      operation: string;
      /**
       *
       * @indexed: false
       **/
      error: string;
      /**
       *
       * @indexed: false
       **/
      caller: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;
}
