// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type {
  InkPrimitivesLangError,
  PortfolioPortfolioState,
  PortfolioFeeConfiguration,
  SharedError,
  PortfolioTokenHolding,
  PortfolioPortfolioComposition,
} from "./types.js";

export interface ContractQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractQuery<ChainApi, Type> {
  /**
   * Get portfolio owner
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Get current portfolio state
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x3d1e8968
   **/
  getState: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        PortfolioPortfolioState,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get deployment timestamp
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2c258e50
   **/
  getDeploymentTimestamp: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get total number of tokens held
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x114748a6
   **/
  getTotalTokensHeld: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get list of token IDs currently held
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x96436f0b
   **/
  getHeldTokenIds: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<number>, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Check if portfolio is emergency paused
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x23e4a85f
   **/
  isEmergencyPaused: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get fee configuration
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x12136f86
   **/
  getFeeConfig: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        PortfolioFeeConfiguration,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get total fees collected
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xc7a8291f
   **/
  getTotalFeesCollected: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Set portfolio state (owner only)
   *
   * @param {PortfolioPortfolioState} newState
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x62fac83c
   **/
  setState: GenericContractQueryCall<
    ChainApi,
    (
      newState: PortfolioPortfolioState,
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Emergency pause all operations (owner only)
   *
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x4ec112d9
   **/
  emergencyPause: GenericContractQueryCall<
    ChainApi,
    (
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Resume operations after emergency pause (owner only)
   *
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0xd777a238
   **/
  resumeOperations: GenericContractQueryCall<
    ChainApi,
    (
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Update fee configuration (owner only)
   *
   * @param {PortfolioFeeConfiguration} newConfig
   * @param {ContractCallOptions} options
   *
   * @selector 0xbe172e69
   **/
  setFeeConfig: GenericContractQueryCall<
    ChainApi,
    (
      newConfig: PortfolioFeeConfiguration,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Set registry contract address (owner only)
   *
   * @param {H160} registry
   * @param {ContractCallOptions} options
   *
   * @selector 0xd753ec74
   **/
  setRegistryContract: GenericContractQueryCall<
    ChainApi,
    (
      registry: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Set token contract address (owner only)
   *
   * @param {H160} token
   * @param {ContractCallOptions} options
   *
   * @selector 0x2fc3cfae
   **/
  setTokenContract: GenericContractQueryCall<
    ChainApi,
    (
      token: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Set DEX contract address (owner only)
   *
   * @param {H160} dex
   * @param {ContractCallOptions} options
   *
   * @selector 0xb53ae601
   **/
  setDexContract: GenericContractQueryCall<
    ChainApi,
    (
      dex: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Set oracle contract address (owner only)
   *
   * @param {H160} oracle
   * @param {ContractCallOptions} options
   *
   * @selector 0x56062dea
   **/
  setOracleContract: GenericContractQueryCall<
    ChainApi,
    (
      oracle: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get contract references
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x541952c6
   **/
  getRegistryContract: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xad4a397f
   **/
  getTokenContract: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8b6aff5f
   **/
  getDexContract: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x47d22829
   **/
  getOracleContract: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Add a new token holding to the portfolio (owner only)
   *
   * @param {number} tokenId
   * @param {bigint} amount
   * @param {number} targetWeightBp
   * @param {ContractCallOptions} options
   *
   * @selector 0x8c8c0dbb
   **/
  addTokenHolding: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      amount: bigint,
      targetWeightBp: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Update an existing token holding (owner only)
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newTargetWeightBp
   * @param {ContractCallOptions} options
   *
   * @selector 0xcb447ba5
   **/
  updateTokenHolding: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      newAmount: bigint,
      newTargetWeightBp: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Remove a token holding from the portfolio (owner only)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x8499ff26
   **/
  removeTokenHolding: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get specific token holding data
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x1aa480ab
   **/
  getTokenHolding: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        PortfolioTokenHolding | undefined,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Check if portfolio holds a specific token
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x6327cf7d
   **/
  holdsToken: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get complete portfolio composition
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x95c95f2d
   **/
  getPortfolioComposition: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        PortfolioPortfolioComposition,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get token holding amount only (convenience method)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xfe250e33
   **/
  getTokenAmount: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get token target weight only (convenience method)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xb07c6e53
   **/
  getTokenTargetWeight: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get all holdings as simple (token_id, amount) pairs
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xe7bdd0ac
   **/
  getAllHoldings: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<[number, bigint]>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get all target weights as (token_id, weight_bp) pairs
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xfe275351
   **/
  getAllTargetWeights: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<[number, number]>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Calculate total target weight allocation across all holdings
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf5ecafdc
   **/
  getTotalTargetWeight: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Check if portfolio has any holdings
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xc4860b34
   **/
  hasHoldings: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get portfolio statistics
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6a0fdd74
   **/
  getPortfolioStats: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        [number, number, number],
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Add multiple token holdings in a single transaction (owner only)
   *
   * @param {Array<[number, bigint, number]>} holdingsData
   * @param {ContractCallOptions} options
   *
   * @selector 0xe0e682d6
   **/
  addMultipleHoldings: GenericContractQueryCall<
    ChainApi,
    (
      holdingsData: Array<[number, bigint, number]>,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Update multiple token amounts in a single transaction (owner only)
   *
   * @param {Array<[number, bigint]>} updates
   * @param {ContractCallOptions} options
   *
   * @selector 0xc6ac54cd
   **/
  updateMultipleAmounts: GenericContractQueryCall<
    ChainApi,
    (
      updates: Array<[number, bigint]>,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Set maximum tokens limit (owner only)
   *
   * @param {number} maxTokens
   * @param {ContractCallOptions} options
   *
   * @selector 0x20cbe039
   **/
  setMaxTokens: GenericContractQueryCall<
    ChainApi,
    (
      maxTokens: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get maximum tokens limit
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbba8005a
   **/
  getMaxTokens: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Check if portfolio can accept more tokens
   *
   * @param {number} count
   * @param {ContractCallOptions} options
   *
   * @selector 0xbd857de4
   **/
  canAddTokens: GenericContractQueryCall<
    ChainApi,
    (
      count: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Validate portfolio weight allocation is correct
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4391adfb
   **/
  validateWeightAllocation: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<boolean, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get remaining weight allocation capacity
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xb49fd71c
   **/
  getRemainingWeightCapacity: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Initialize base portfolio value after first tokens are added (owner only)
   * This sets the immutable baseline for performance tracking
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf43ecec5
   **/
  initializeBasePortfolioValue: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Calculate current index value using the formula:
   * Index Value = (Current Portfolio Value / Base Portfolio Value) × Base Index Value
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4f658088
   **/
  calculateCurrentIndexValue: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get current cached index value (fast query)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x19c35771
   **/
  getCurrentIndexValue: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Update cached index value with real-time calculation (owner only)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x0b40ddf8
   **/
  updateIndexValue: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get index performance as basis points relative to $100 baseline
   * Returns: +2500 for +25%, -1500 for -15%, etc.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf6b2f5b5
   **/
  getIndexPerformance: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get real-time index performance (recalculates current value)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xdf991260
   **/
  getRealtimeIndexPerformance: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get index base metrics for UI display
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2abe9859
   **/
  getIndexBaseMetrics: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        [bigint, bigint, bigint, boolean],
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get index value in USD (converted via DOT/USD oracle)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xecd07451
   **/
  getIndexValueUsd: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get real-time index value in USD
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x92cc9687
   **/
  getRealtimeIndexValueUsd: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Check if index value data is stale (not updated recently)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xff089403
   **/
  isIndexValueStale: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Get time since last index update in milliseconds
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xdcfa4e18
   **/
  getIndexUpdateAge: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Force index recalculation and update (owner only)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xc65fbd3f
   **/
  refreshIndexValue: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[bigint, number], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get index performance over time periods (if we had historical data)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4d7bbe62
   **/
  getIndexSummary: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[bigint, bigint, number, bigint], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Enable/disable index tracking (owner only)
   *
   * @param {boolean} enabled
   * @param {ContractCallOptions} options
   *
   * @selector 0x720eed85
   **/
  setIndexTracking: GenericContractQueryCall<
    ChainApi,
    (
      enabled: boolean,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Check if index tracking is enabled
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6c0e9ae6
   **/
  isIndexTrackingEnabled: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   * Emergency reset index base value (owner only - use with extreme caution)
   *
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x45ce6272
   **/
  emergencyResetBaseValue: GenericContractQueryCall<
    ChainApi,
    (
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get real-time token price from Registry (public method for external use)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x4be3c386
   **/
  getTokenMarketData: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[bigint, bigint, bigint], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get current market value of a specific token holding
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xbc5b7dca
   **/
  getTokenHoldingValue: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get all holdings with current market values
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa5d51417
   **/
  getHoldingsWithValues: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<Array<[number, bigint, bigint]>, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get active tier tokens for rebalancing decisions
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x74623358
   **/
  getRebalancingTargets: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<Array<number>, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Check if a token is in the active tier
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x4e9adc08
   **/
  isTokenInActiveTier: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<boolean, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Validate portfolio holdings against Registry data
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8b812bc0
   **/
  validateHoldingsAgainstRegistry: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<Array<number>, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get portfolio composition with Registry market data
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa16eda59
   **/
  getPortfolioCompositionWithMarketData: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<PortfolioPortfolioComposition, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get detailed portfolio valuation breakdown
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x202b243e
   **/
  getPortfolioValuationBreakdown: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<Array<[number, bigint, bigint, bigint]>, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Test Registry connection and data availability
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x588c1336
   **/
  testRegistryConnection: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[boolean, number], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;
}
