// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";
import type {
  PortfolioPortfolioState,
  PortfolioFeeConfiguration,
} from "./types.js";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Set portfolio state (owner only)
   *
   * @param {PortfolioPortfolioState} newState
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x62fac83c
   **/
  setState: GenericContractTxCall<
    ChainApi,
    (
      newState: PortfolioPortfolioState,
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Emergency pause all operations (owner only)
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x4ec112d9
   **/
  emergencyPause: GenericContractTxCall<
    ChainApi,
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Resume operations after emergency pause (owner only)
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0xdacb444b
   **/
  emergencyResume: GenericContractTxCall<
    ChainApi,
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update fee configuration (owner only)
   *
   * @param {PortfolioFeeConfiguration} newConfig
   * @param {ContractTxOptions} options
   *
   * @selector 0xbe172e69
   **/
  setFeeConfig: GenericContractTxCall<
    ChainApi,
    (
      newConfig: PortfolioFeeConfiguration,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set registry contract address (owner only)
   *
   * @param {H160} registry
   * @param {ContractTxOptions} options
   *
   * @selector 0xd753ec74
   **/
  setRegistryContract: GenericContractTxCall<
    ChainApi,
    (
      registry: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set token contract address (owner only)
   *
   * @param {H160} token
   * @param {ContractTxOptions} options
   *
   * @selector 0x2fc3cfae
   **/
  setTokenContract: GenericContractTxCall<
    ChainApi,
    (
      token: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set DEX contract address (owner only)
   *
   * @param {H160} dex
   * @param {ContractTxOptions} options
   *
   * @selector 0xb53ae601
   **/
  setDexContract: GenericContractTxCall<
    ChainApi,
    (
      dex: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set oracle contract address (owner only)
   *
   * @param {H160} oracle
   * @param {ContractTxOptions} options
   *
   * @selector 0x56062dea
   **/
  setOracleContract: GenericContractTxCall<
    ChainApi,
    (
      oracle: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Add a new token holding to the portfolio (owner only)
   *
   * @param {number} tokenId
   * @param {bigint} amount
   * @param {number} targetWeightBp
   * @param {ContractTxOptions} options
   *
   * @selector 0x8c8c0dbb
   **/
  addTokenHolding: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      amount: bigint,
      targetWeightBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Remove a token holding from the portfolio (can be called by owner or Registry)
   * This is called when a token becomes Tier::None after grace period
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0x8499ff26
   **/
  removeTokenHolding: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update an existing token holding (owner only)
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newTargetWeightBp
   * @param {ContractTxOptions} options
   *
   * @selector 0xcb447ba5
   **/
  updateTokenHolding: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      newAmount: bigint,
      newTargetWeightBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Add multiple token holdings in a single transaction (owner only)
   *
   * @param {Array<[number, bigint, number]>} holdingsData
   * @param {ContractTxOptions} options
   *
   * @selector 0xe0e682d6
   **/
  addMultipleHoldings: GenericContractTxCall<
    ChainApi,
    (
      holdingsData: Array<[number, bigint, number]>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update multiple token amounts in a single transaction (owner only)
   *
   * @param {Array<[number, bigint]>} updates
   * @param {ContractTxOptions} options
   *
   * @selector 0xc6ac54cd
   **/
  updateMultipleAmounts: GenericContractTxCall<
    ChainApi,
    (
      updates: Array<[number, bigint]>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set maximum tokens limit (owner only)
   *
   * @param {number} maxTokens
   * @param {ContractTxOptions} options
   *
   * @selector 0x20cbe039
   **/
  setMaxTokens: GenericContractTxCall<
    ChainApi,
    (
      maxTokens: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Initialize base portfolio value after first tokens are added (owner only)
   * This sets the immutable baseline for performance tracking
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xf43ecec5
   **/
  initializeBasePortfolioValue: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update cached index value with real-time calculation (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x0b40ddf8
   **/
  updateIndexValue: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Force index recalculation and update (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xc65fbd3f
   **/
  refreshIndexValue: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Enable/disable index tracking (owner only)
   *
   * @param {boolean} enabled
   * @param {ContractTxOptions} options
   *
   * @selector 0x720eed85
   **/
  setIndexTracking: GenericContractTxCall<
    ChainApi,
    (
      enabled: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set index base value (owner only)
   *
   * @param {bigint} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x8b4a4890
   **/
  setIndexBaseValue: GenericContractTxCall<
    ChainApi,
    (
      newValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set liquidity buffer (owner only)
   *
   * @param {bigint} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xd7460457
   **/
  setLiquidityBuffer: GenericContractTxCall<
    ChainApi,
    (
      newValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set max single position (owner only)
   *
   * @param {number} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xc861a01c
   **/
  setMaxSinglePosition: GenericContractTxCall<
    ChainApi,
    (
      newValue: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set max slippage (owner only)
   *
   * @param {number} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x6cc09ca6
   **/
  setMaxSlippage: GenericContractTxCall<
    ChainApi,
    (
      newValue: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set rebalance threshold (owner only)
   *
   * @param {number} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xeba65fa0
   **/
  setRebalanceThreshold: GenericContractTxCall<
    ChainApi,
    (
      newValue: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Emergency reset index base value (owner only - use with extreme caution)
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x45ce6272
   **/
  emergencyResetBaseValue: GenericContractTxCall<
    ChainApi,
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Enable the 4-week moving average system (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x3f1075e6
   **/
  enableMovingAverageSystem: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Disable the 4-week moving average system (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x8361254b
   **/
  disableMovingAverageSystem: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Take weekly snapshot for all held tokens (owner or automated)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xcadf5ac0
   **/
  takeWeeklySnapshot: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Enable the monthly rebalancing system (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xfb477e2c
   **/
  enableRebalancing: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Disable the monthly rebalancing system (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x85debd84
   **/
  disableRebalancing: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Execute monthly rebalancing with 20% max shift cap
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xce20575e
   **/
  executeMonthlyRebalance: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set max monthly shift (owner only)
   *
   * @param {number} maxShiftBp
   * @param {ContractTxOptions} options
   *
   * @selector 0x9a9ccf5b
   **/
  setMaxMonthlyShift: GenericContractTxCall<
    ChainApi,
    (
      maxShiftBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set USDC contract address (owner only)
   *
   * @param {H160} usdc
   * @param {ContractTxOptions} options
   *
   * @selector 0x46e77b11
   **/
  setUsdcContract: GenericContractTxCall<
    ChainApi,
    (
      usdc: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set Staking contract address (owner only)
   *
   * @param {H160} staking
   * @param {ContractTxOptions} options
   *
   * @selector 0x00e16ab8
   **/
  setStakingContract: GenericContractTxCall<
    ChainApi,
    (
      staking: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Execute a manual swap (owner only, for emergency or manual operations)
   *
   * @param {H160} tokenIn
   * @param {H160} tokenOut
   * @param {bigint} amountIn
   * @param {ContractTxOptions} options
   *
   * @selector 0xf8a09e9c
   **/
  executeSwap: GenericContractTxCall<
    ChainApi,
    (
      tokenIn: H160,
      tokenOut: H160,
      amountIn: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set fee treasury address (owner only)
   *
   * @param {H160} treasury
   * @param {ContractTxOptions} options
   *
   * @selector 0x5667983d
   **/
  setFeeTreasury: GenericContractTxCall<
    ChainApi,
    (
      treasury: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Collect streaming fee (anyone can call, but fees go to treasury)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x0f716a8a
   **/
  collectStreamingFee: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set streaming fee collection interval (owner only)
   *
   * @param {bigint} intervalMs
   * @param {ContractTxOptions} options
   *
   * @selector 0xc058dfca
   **/
  setStreamingFeeInterval: GenericContractTxCall<
    ChainApi,
    (
      intervalMs: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Buy W3PI tokens by depositing USDC
   * Flow: User sends USDC → deduct 0.55% fee → swap to basket tokens → mint W3PI
   *
   * @param {bigint} usdcAmount
   * @param {ContractTxOptions} options
   *
   * @selector 0x58015b4d
   **/
  buyW3pi: GenericContractTxCall<
    ChainApi,
    (
      usdcAmount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Sell W3PI tokens and receive USDC
   * Flow: User sends W3PI → burn W3PI → swap basket tokens to USDC → deduct 0.95% fee → return USDC
   *
   * @param {bigint} w3piAmount
   * @param {ContractTxOptions} options
   *
   * @selector 0x8cb25829
   **/
  sellW3pi: GenericContractTxCall<
    ChainApi,
    (
      w3piAmount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Receive reallocation from Staking contract (zombie stake cleanup)
   * This function receives USDC value from liquidated zombie stakes
   * and redistributes it proportionally to active holdings
   *
   * @param {bigint} usdcAmount
   * @param {ContractTxOptions} options
   *
   * @selector 0x42ef969b
   **/
  receiveReallocation: GenericContractTxCall<
    ChainApi,
    (
      usdcAmount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
