// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";
import type {
  PortfolioPortfolioState,
  PortfolioFeeConfiguration,
} from "./types.js";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Set portfolio state (owner only)
   *
   * @param {PortfolioPortfolioState} newState
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x62fac83c
   **/
  setState: GenericContractTxCall<
    ChainApi,
    (
      newState: PortfolioPortfolioState,
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Emergency pause all operations (owner only)
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x4ec112d9
   **/
  emergencyPause: GenericContractTxCall<
    ChainApi,
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Resume operations after emergency pause (owner only)
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0xd777a238
   **/
  resumeOperations: GenericContractTxCall<
    ChainApi,
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update fee configuration (owner only)
   *
   * @param {PortfolioFeeConfiguration} newConfig
   * @param {ContractTxOptions} options
   *
   * @selector 0xbe172e69
   **/
  setFeeConfig: GenericContractTxCall<
    ChainApi,
    (
      newConfig: PortfolioFeeConfiguration,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set registry contract address (owner only)
   *
   * @param {H160} registry
   * @param {ContractTxOptions} options
   *
   * @selector 0xd753ec74
   **/
  setRegistryContract: GenericContractTxCall<
    ChainApi,
    (
      registry: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set token contract address (owner only)
   *
   * @param {H160} token
   * @param {ContractTxOptions} options
   *
   * @selector 0x2fc3cfae
   **/
  setTokenContract: GenericContractTxCall<
    ChainApi,
    (
      token: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set DEX contract address (owner only)
   *
   * @param {H160} dex
   * @param {ContractTxOptions} options
   *
   * @selector 0xb53ae601
   **/
  setDexContract: GenericContractTxCall<
    ChainApi,
    (
      dex: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set oracle contract address (owner only)
   *
   * @param {H160} oracle
   * @param {ContractTxOptions} options
   *
   * @selector 0x56062dea
   **/
  setOracleContract: GenericContractTxCall<
    ChainApi,
    (
      oracle: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Add a new token holding to the portfolio (owner only)
   *
   * @param {number} tokenId
   * @param {bigint} amount
   * @param {number} targetWeightBp
   * @param {ContractTxOptions} options
   *
   * @selector 0x8c8c0dbb
   **/
  addTokenHolding: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      amount: bigint,
      targetWeightBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update an existing token holding (owner only)
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newTargetWeightBp
   * @param {ContractTxOptions} options
   *
   * @selector 0xcb447ba5
   **/
  updateTokenHolding: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      newAmount: bigint,
      newTargetWeightBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Remove a token holding from the portfolio (owner only)
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0x8499ff26
   **/
  removeTokenHolding: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Add multiple token holdings in a single transaction (owner only)
   *
   * @param {Array<[number, bigint, number]>} holdingsData
   * @param {ContractTxOptions} options
   *
   * @selector 0xe0e682d6
   **/
  addMultipleHoldings: GenericContractTxCall<
    ChainApi,
    (
      holdingsData: Array<[number, bigint, number]>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update multiple token amounts in a single transaction (owner only)
   *
   * @param {Array<[number, bigint]>} updates
   * @param {ContractTxOptions} options
   *
   * @selector 0xc6ac54cd
   **/
  updateMultipleAmounts: GenericContractTxCall<
    ChainApi,
    (
      updates: Array<[number, bigint]>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set maximum tokens limit (owner only)
   *
   * @param {number} maxTokens
   * @param {ContractTxOptions} options
   *
   * @selector 0x20cbe039
   **/
  setMaxTokens: GenericContractTxCall<
    ChainApi,
    (
      maxTokens: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Initialize base portfolio value after first tokens are added (owner only)
   * This sets the immutable baseline for performance tracking
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xf43ecec5
   **/
  initializeBasePortfolioValue: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Update cached index value with real-time calculation (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x0b40ddf8
   **/
  updateIndexValue: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Force index recalculation and update (owner only)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xc65fbd3f
   **/
  refreshIndexValue: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Enable/disable index tracking (owner only)
   *
   * @param {boolean} enabled
   * @param {ContractTxOptions} options
   *
   * @selector 0x720eed85
   **/
  setIndexTracking: GenericContractTxCall<
    ChainApi,
    (
      enabled: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Emergency reset index base value (owner only - use with extreme caution)
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x45ce6272
   **/
  emergencyResetBaseValue: GenericContractTxCall<
    ChainApi,
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
