// Generated by dedot cli

import type { FixedArray, H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type PortfolioTokenHolding = {
  amount: bigint;
  targetWeightBp: number;
  lastRebalance: bigint;
  feesCollected: bigint;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type PortfolioTokenSnapshotHistory = {
  snapshots: FixedArray<PortfolioWeeklySnapshot, 4>;
  currentIndex: number;
  snapshotCount: number;
};

export type PortfolioWeeklySnapshot = {
  marketCap: bigint;
  price: bigint;
  timestamp: bigint;
  weekIndex: number;
};

export type Portfolio = {
  owner: H160;
  state: PortfolioPortfolioState;
  deploymentTimestamp: bigint;
  holdings: { get(arg: number): Promise<PortfolioTokenHolding | undefined> };
  heldTokenIds: Array<number>;
  totalTokensHeld: number;
  indexBaseValue: bigint;
  basePortfolioValue: bigint;
  currentIndexValue: bigint;
  lastIndexUpdate: bigint;
  indexTrackingEnabled: boolean;
  feeConfig: PortfolioFeeConfiguration;
  collectedFees: { get(arg: number): Promise<bigint | undefined> };
  lastStreamingFee: { get(arg: H160): Promise<bigint | undefined> };
  feeBeneficiaries: { get(arg: H160): Promise<number | undefined> };
  totalFeesCollected: bigint;
  registryContract?: H160 | undefined;
  tokenContract?: H160 | undefined;
  dexContract?: H160 | undefined;
  oracleContract?: H160 | undefined;
  maxTokens: number;
  minPortfolioValue: bigint;
  lastRebalance: bigint;
  rebalanceThresholdBp: number;
  emergencyPaused: boolean;
  minLiquidityBuffer: bigint;
  usdcBalance: bigint;
  maxSinglePositionBp: number;
  maxSlippageBp: number;
  tokenSnapshots: {
    get(arg: number): Promise<PortfolioTokenSnapshotHistory | undefined>;
  };
  lastSnapshotTimestamp: bigint;
  snapshotIntervalMs: bigint;
  movingAverageEnabled: boolean;
  lastMonthlyRebalance: bigint;
  monthlyRebalanceIntervalMs: bigint;
  maxMonthlyShiftBp: number;
  currentMonthShiftBp: number;
  rebalancingEnabled: boolean;
  lastStreamingFeeCollection: bigint;
  totalStreamingFeesCollected: bigint;
  streamingFeeIntervalMs: bigint;
  feeTreasury?: H160 | undefined;
  usdcContract?: H160 | undefined;
  stakingContract?: H160 | undefined;
  reentrancyGuard: SharedUtilsReentrancyGuard;
};

export type PortfolioPortfolioState =
  | "Active"
  | "Paused"
  | "Maintenance"
  | "Emergency";

export type PortfolioFeeConfiguration = {
  buyFeeBp: number;
  sellFeeBp: number;
  streamingFeeBp: number;
};

export type SharedUtilsReentrancyGuard = { executing: boolean };

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance"
  | "ContractPaused"
  | "CrossContractCallFailed"
  | "TransferFailed"
  | "InvalidParameters";

export type PortfolioPortfolioComposition = {
  totalTokens: number;
  totalValue: bigint;
  holdings: Array<[number, PortfolioTokenHolding]>;
};

export type PortfolioRebalanceOrder = {
  tokenId: number;
  tokenContract: H160;
  currentWeightBp: number;
  targetWeightBp: number;
  weightDeltaBp: number;
  tradeAmount: bigint;
  isBuy: boolean;
};

export type PortfolioRebalanceResult = {
  totalOrders: number;
  executedOrders: number;
  valueBefore: bigint;
  valueAfter: bigint;
  totalWeightShiftedBp: number;
  timestamp: bigint;
};
