// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  GenericInstantiateSubmittableExtrinsic,
} from "dedot/contracts";
import type { OracleValidationConfig } from "./types.js";

export interface ConstructorTx<ChainApi extends GenericSubstrateApi>
  extends GenericConstructorTx<ChainApi> {
  /**
   * Constructor
   *
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      options: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Constructor with sample data and custom config
   *
   * @param {OracleValidationConfig} config
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x7335a10e
   **/
  newWithConfig: GenericConstructorTxCall<
    ChainApi,
    (
      config: OracleValidationConfig,
      options: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi>
  >;
}
