// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Result } from "dedot/codecs";
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
} from "dedot/contracts";
import type {
  InkPrimitivesLangError,
  OracleValidationConfig,
} from "./types.js";

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi>
  extends GenericConstructorQuery<ChainApi> {
  /**
   * Constructor
   *
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      options?: ConstructorCallOptions,
    ) => Promise<
      GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>
    >
  >;

  /**
   * Constructor with sample data and custom config
   *
   * @param {OracleValidationConfig} config
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x7335a10e
   **/
  newWithConfig: GenericConstructorQueryCall<
    ChainApi,
    (
      config: OracleValidationConfig,
      options?: ConstructorCallOptions,
    ) => Promise<
      GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>
    >
  >;
}
