// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
} from "dedot/contracts";

export interface ContractEvents<ChainApi extends GenericSubstrateApi>
  extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0xeed6bc34d4008b4c2ac6b8c0313a7cfd87293ee64de35fdcae1b5f900cbe1bf3
   **/
  PriceUpdated: GenericContractEvent<
    "PriceUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      token: AccountId32;
      /**
       *
       * @indexed: false
       **/
      price: bigint;
    }
  >;

  /**
   *
   * @signature_topic: 0x818d2ffa189e241e06a657bd663f9e27b1b8c42c6bcafa44c55cb625aea89f57
   **/
  MarketDataUpdated: GenericContractEvent<
    "MarketDataUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      token: AccountId32;
      /**
       *
       * @indexed: false
       **/
      marketCap: bigint;
      /**
       *
       * @indexed: false
       **/
      volume: bigint;
    }
  >;
}
