// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, Result, AccountId32 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from "dedot/contracts";
import type { InkPrimitivesLangError, SharedError } from "./types.js";

export interface ContractQuery<ChainApi extends GenericSubstrateApi>
  extends GenericContractQuery<ChainApi> {
  /**
   * Get token price
   *
   * @param {AccountId32Like} token
   * @param {ContractCallOptions} options
   *
   * @selector 0xf23d4b6c
   **/
  getPrice: GenericContractQueryCall<
    ChainApi,
    (
      token: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        bigint | undefined,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Get market cap
   *
   * @param {AccountId32Like} token
   * @param {ContractCallOptions} options
   *
   * @selector 0xe298cd11
   **/
  getMarketCap: GenericContractQueryCall<
    ChainApi,
    (
      token: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        bigint | undefined,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Get market volume
   *
   * @param {AccountId32Like} token
   * @param {ContractCallOptions} options
   *
   * @selector 0xb92a26ef
   **/
  getMarketVolume: GenericContractQueryCall<
    ChainApi,
    (
      token: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        bigint | undefined,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Update price data (owner only)
   *
   * @param {AccountId32Like} token
   * @param {bigint} price
   * @param {ContractCallOptions} options
   *
   * @selector 0xf83f798f
   **/
  updatePrice: GenericContractQueryCall<
    ChainApi,
    (
      token: AccountId32Like,
      price: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Update market data (owner only)
   *
   * @param {AccountId32Like} token
   * @param {bigint} marketCap
   * @param {bigint} volume
   * @param {ContractCallOptions} options
   *
   * @selector 0x874514b8
   **/
  updateMarketData: GenericContractQueryCall<
    ChainApi,
    (
      token: AccountId32Like,
      marketCap: bigint,
      volume: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Get the owner
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<AccountId32, ContractCallResult<ChainApi>>
    >
  >;
}
