// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   * Update price data (owner only)
   *
   * @param {AccountId32Like} token
   * @param {bigint} price
   * @param {ContractTxOptions} options
   *
   * @selector 0xf83f798f
   **/
  updatePrice: GenericContractTxCall<
    ChainApi,
    (
      token: AccountId32Like,
      price: bigint,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Update market data (owner only)
   *
   * @param {AccountId32Like} token
   * @param {bigint} marketCap
   * @param {bigint} volume
   * @param {ContractTxOptions} options
   *
   * @selector 0x874514b8
   **/
  updateMarketData: GenericContractTxCall<
    ChainApi,
    (
      token: AccountId32Like,
      marketCap: bigint,
      volume: bigint,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
