// Generated by dedot cli

import type { AccountId32Like, AccountId32 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Oracle = {
  prices: { get(arg: AccountId32Like): Promise<bigint | undefined> };
  marketCaps: { get(arg: AccountId32Like): Promise<bigint | undefined> };
  marketVolumes: { get(arg: AccountId32Like): Promise<bigint | undefined> };
  owner: AccountId32;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "TokenNotFound"
  | "OracleCallFailed"
  | "InvalidParameter"
  | "InsufficientBalance";

export type InkEnvNoChainExtension = null;
