// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";
import type { OracleValidationConfig } from "./types.js";

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<ChainApi, Type> {
  /**
   * Constructor
   *
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;

  /**
   * Constructor with sample data and custom config
   *
   * @param {OracleValidationConfig} config
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x7335a10e
   **/
  newWithConfig: GenericConstructorTxCall<
    ChainApi,
    (
      config: OracleValidationConfig,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;
}
