// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   *
   *
   **/
  PriceUpdated: GenericContractEvent<
    "PriceUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      token: AccountId32;
      /**
       *
       * @indexed: false
       **/
      price: bigint;
      /**
       *
       * @indexed: false
       **/
      marketCap: bigint;
      /**
       *
       * @indexed: false
       **/
      volume: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  UpdaterAdded: GenericContractEvent<
    "UpdaterAdded",
    {
      /**
       *
       * @indexed: true
       **/
      updater: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  ConfigUpdated: GenericContractEvent<
    "ConfigUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      maxDeviationBp: number;
      /**
       *
       * @indexed: false
       **/
      stalenessThreshold: bigint;
      /**
       *
       * @indexed: false
       **/
      minUpdateInterval: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  EmergencyPause: GenericContractEvent<
    "EmergencyPause",
    {
      /**
       *
       * @indexed: false
       **/
      paused: boolean;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  UpdaterRemoved: GenericContractEvent<
    "UpdaterRemoved",
    {
      /**
       *
       * @indexed: true
       **/
      updater: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  ValidationFailed: GenericContractEvent<
    "ValidationFailed",
    {
      /**
       *
       * @indexed: true
       **/
      token: AccountId32;
      /**
       *
       * @indexed: false
       **/
      reason: string;
      /**
       *
       * @indexed: false
       **/
      attemptedPrice: bigint;
      /**
       *
       * @indexed: false
       **/
      currentPrice: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  MarketDataUpdated: GenericContractEvent<
    "MarketDataUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      token: AccountId32;
      /**
       *
       * @indexed: false
       **/
      marketCap: bigint;
      /**
       *
       * @indexed: false
       **/
      volume: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  DotUsdPriceUpdated: GenericContractEvent<
    "DotUsdPriceUpdated",
    {
      /**
       * USD price in scaled format (e.g., 6.50 USD = 6_500_000_000 with 9 decimals)
       *
       * @indexed: false
       **/
      usdPrice: bigint;
      /**
       * Timestamp of the update
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       * Account that updated the price
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  DotPriceValidationFailed: GenericContractEvent<
    "DotPriceValidationFailed",
    {
      /**
       *
       * @indexed: false
       **/
      reason: string;
      /**
       *
       * @indexed: false
       **/
      attemptedPrice: bigint;
      /**
       *
       * @indexed: false
       **/
      currentPrice: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;
}
