// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";
import type { SharedTier, SharedRole, SharedError } from "./types.js";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   *
   *
   **/
  TokenAdded: GenericContractEvent<
    "TokenAdded",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: AccountId32;
      /**
       *
       * @indexed: false
       **/
      oracleContract: AccountId32;
      /**
       *
       * @indexed: false
       **/
      initialTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      addedBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenUpdated: GenericContractEvent<
    "TokenUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      balance: bigint;
      /**
       *
       * @indexed: false
       **/
      weightInvestment: number;
      /**
       *
       * @indexed: false
       **/
      oldTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      newTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenRemoved: GenericContractEvent<
    "TokenRemoved",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: AccountId32;
      /**
       *
       * @indexed: false
       **/
      tier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      removedBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenTierChanged: GenericContractEvent<
    "TokenTierChanged",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: AccountId32;
      /**
       *
       * @indexed: false
       **/
      oldTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      newTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      marketCap: bigint;
      /**
       *
       * @indexed: false
       **/
      volume: bigint;
      /**
       *
       * @indexed: false
       **/
      reason: string;
    },
    Type
  >;

  /**
   *
   *
   **/
  ActiveTierShifted: GenericContractEvent<
    "ActiveTierShifted",
    {
      /**
       *
       * @indexed: false
       **/
      oldTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      newTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      triggerReason: string;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      tokensQualifying: number;
      /**
       *
       * @indexed: false
       **/
      totalTokens: number;
    },
    Type
  >;

  /**
   *
   *
   **/
  TierThresholdsUpdated: GenericContractEvent<
    "TierThresholdsUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      newUsdRate: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  GracePeriodStarted: GenericContractEvent<
    "GracePeriodStarted",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      currentTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      pendingTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      graceEndTime: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  GracePeriodUpdated: GenericContractEvent<
    "GracePeriodUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      oldPeriodMs: bigint;
      /**
       *
       * @indexed: false
       **/
      newPeriodMs: bigint;
      /**
       *
       * @indexed: false
       **/
      updatedBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  EmergencyTierOverride: GenericContractEvent<
    "EmergencyTierOverride",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: AccountId32;
      /**
       *
       * @indexed: false
       **/
      oldTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      newTier: SharedTier;
      /**
       *
       * @indexed: false
       **/
      overriddenBy: AccountId32;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      reason: string;
    },
    Type
  >;

  /**
   *
   *
   **/
  RoleGranted: GenericContractEvent<
    "RoleGranted",
    {
      /**
       *
       * @indexed: true
       **/
      role: SharedRole;
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      grantedBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  RoleRevoked: GenericContractEvent<
    "RoleRevoked",
    {
      /**
       *
       * @indexed: true
       **/
      role: SharedRole;
      /**
       *
       * @indexed: true
       **/
      account: AccountId32;
      /**
       *
       * @indexed: false
       **/
      revokedBy: AccountId32;
    },
    Type
  >;

  /**
   *
   *
   **/
  OperationFailed: GenericContractEvent<
    "OperationFailed",
    {
      /**
       *
       * @indexed: false
       **/
      operation: string;
      /**
       *
       * @indexed: false
       **/
      error: SharedError;
      /**
       *
       * @indexed: false
       **/
      caller: AccountId32;
    },
    Type
  >;
}
