// Generated by dedot cli

import type { H160, AccountId32 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type RegistryEnhancedTokenData = {
  tokenContract: H160;
  oracleContract: H160;
  balance: bigint;
  weightInvestment: number;
  tier: SharedTier;
  tierChangeTimestamp?: bigint | undefined;
  pendingTierChange?: SharedTier | undefined;
};

export type SharedTier = "None" | "Tier1" | "Tier2" | "Tier3" | "Tier4";

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type SharedRole =
  | "TokenManager"
  | "TokenUpdater"
  | "EmergencyController";

export type Registry = {
  tokens: { get(arg: number): Promise<RegistryEnhancedTokenData | undefined> };
  tokenContractToId: { get(arg: H160): Promise<number | undefined> };
  roleMembers: { get(arg: [SharedRole, H160]): Promise<boolean | undefined> };
  nextTokenId: number;
  owner: H160;
  activeTier: SharedTier;
  tierThresholds: RegistryTierThresholds;
  tierDistribution: { get(arg: SharedTier): Promise<number | undefined> };
  lastTierChange?: bigint | undefined;
  dotUsdOracle?: H160 | undefined;
  gracePeriodMs: bigint;
};

export type RegistryTierThresholds = {
  tier1MarketCapUsd: bigint;
  tier1VolumeUsd: bigint;
  tier2MarketCapUsd: bigint;
  tier2VolumeUsd: bigint;
  tier3MarketCapUsd: bigint;
  tier3VolumeUsd: bigint;
  tier4MarketCapUsd: bigint;
  tier4VolumeUsd: bigint;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance"
  | "ContractPaused"
  | "CrossContractCallFailed"
  | "TransferFailed"
  | "InvalidParameters";

export type SharedEnrichedTokenData = {
  tokenContract: AccountId32;
  oracleContract: AccountId32;
  balance: bigint;
  weightInvestment: number;
  tier: number;
  marketCap: bigint;
  marketVolume: bigint;
  price: bigint;
};

export type SharedTokenData = {
  tokenContract: AccountId32;
  oracleContract: AccountId32;
  balance: bigint;
  weightInvestment: number;
  tier: number;
};
