// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
} from "dedot/contracts";

export interface ContractEvents<ChainApi extends GenericSubstrateApi>
  extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0x78f872a9f1c19bd5cc0663556269594976c192cb5585bc2bb82dbbc24535bcda
   **/
  TokenAdded: GenericContractEvent<
    "TokenAdded",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      tokenContract: AccountId32;
      /**
       *
       * @indexed: false
       **/
      oracleContract: AccountId32;
    }
  >;

  /**
   *
   * @signature_topic: 0xccd85863adc46ac076050b673e9e7f386c96146d71f20068fc83c3b0082e453d
   **/
  TokenUpdated: GenericContractEvent<
    "TokenUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      balance: bigint;
      /**
       *
       * @indexed: false
       **/
      weightInvestment: number;
      /**
       *
       * @indexed: false
       **/
      tier: number;
    }
  >;
}
