// Generated by dedot cli

import type {
  VersionedGenericSubstrateApi,
  RpcVersion,
  RpcV2,
} from "dedot/types";
import type { GenericContractApi, WithLazyStorage } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import type { InkPrimitivesLangError, Registry } from "./types.js";
import { ContractQuery } from "./query.js";
import { ContractTx } from "./tx.js";
import { ConstructorQuery } from "./constructor-query.js";
import { ConstructorTx } from "./constructor-tx.js";
import { ContractEvents } from "./events.js";

export * from "./types.js";

/**
 * @name: RegistryContractApi
 * @contractName: registry
 * @contractVersion: 0.1.0
 * @authors: 3dln <ashcan@3dln.com>
 * @language: ink! 5.1.1
 **/
export interface RegistryContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends GenericContractApi<Rv, ChainApi> {
  query: ContractQuery<ChainApi[Rv]>;
  tx: ContractTx<ChainApi[Rv]>;
  constructorQuery: ConstructorQuery<ChainApi[Rv]>;
  constructorTx: ConstructorTx<ChainApi[Rv]>;
  events: ContractEvents<ChainApi[Rv]>;
  storage: {
    root(): Promise<Registry>;
    lazy(): WithLazyStorage<Registry>;
  };

  types: {
    RootStorage: Registry;
    LazyStorage: WithLazyStorage<Registry>;
    LangError: InkPrimitivesLangError;
    ChainApi: ChainApi[Rv];
  };
}
