// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, Result, AccountId32 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from "dedot/contracts";
import type {
  SharedError,
  InkPrimitivesLangError,
  SharedEnrichedTokenData,
  SharedTokenData,
} from "./types.js";

export interface ContractQuery<ChainApi extends GenericSubstrateApi>
  extends GenericContractQuery<ChainApi> {
  /**
   * Add a new token to the registry
   *
   * @param {AccountId32Like} tokenContract
   * @param {AccountId32Like} oracleContract
   * @param {ContractCallOptions} options
   *
   * @selector 0x84731716
   **/
  addToken: GenericContractQueryCall<
    ChainApi,
    (
      tokenContract: AccountId32Like,
      oracleContract: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, SharedError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Get token data with live oracle prices
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xecb3f7d0
   **/
  getTokenData: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<SharedEnrichedTokenData, SharedError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Update token balance and investment data
   *
   * @param {number} tokenId
   * @param {bigint} balance
   * @param {number} weightInvestment
   * @param {number} tier
   * @param {ContractCallOptions} options
   *
   * @selector 0x90c3ef3a
   **/
  updateToken: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      balance: bigint,
      weightInvestment: number,
      tier: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   * Get total number of registered tokens
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x744362af
   **/
  getTokenCount: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >
  >;

  /**
   * Get the owner
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<AccountId32, ContractCallResult<ChainApi>>
    >
  >;

  /**
   * Check if a token exists
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x88baeb9e
   **/
  tokenExists: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<boolean, ContractCallResult<ChainApi>>
    >
  >;

  /**
   * Get basic token data without oracle calls
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x312e4a2b
   **/
  getBasicTokenData: GenericContractQueryCall<
    ChainApi,
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<SharedTokenData, SharedError>,
        ContractCallResult<ChainApi>
      >
    >
  >;
}
