// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   * Add a new token to the registry
   *
   * @param {AccountId32Like} tokenContract
   * @param {AccountId32Like} oracleContract
   * @param {ContractTxOptions} options
   *
   * @selector 0x84731716
   **/
  addToken: GenericContractTxCall<
    ChainApi,
    (
      tokenContract: AccountId32Like,
      oracleContract: AccountId32Like,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Update token balance and investment data
   *
   * @param {number} tokenId
   * @param {bigint} balance
   * @param {number} weightInvestment
   * @param {number} tier
   * @param {ContractTxOptions} options
   *
   * @selector 0x90c3ef3a
   **/
  updateToken: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      balance: bigint,
      weightInvestment: number,
      tier: number,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
