// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";
import type { SharedRole } from "./types.js";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   * Grant a role to an account (owner only)
   *
   * @param {SharedRole} role
   * @param {AccountId32Like} account
   * @param {ContractTxOptions} options
   *
   * @selector 0x2aabfab5
   **/
  grantRole: GenericContractTxCall<
    ChainApi,
    (
      role: SharedRole,
      account: AccountId32Like,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Revoke a role from an account (owner only)
   *
   * @param {SharedRole} role
   * @param {AccountId32Like} account
   * @param {ContractTxOptions} options
   *
   * @selector 0x35e1ef4a
   **/
  revokeRole: GenericContractTxCall<
    ChainApi,
    (
      role: SharedRole,
      account: AccountId32Like,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Add a new token to the registry
   *
   * @param {AccountId32Like} tokenContract
   * @param {AccountId32Like} oracleContract
   * @param {ContractTxOptions} options
   *
   * @selector 0x84731716
   **/
  addToken: GenericContractTxCall<
    ChainApi,
    (
      tokenContract: AccountId32Like,
      oracleContract: AccountId32Like,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Update token balance and investment data
   *
   * @param {number} tokenId
   * @param {bigint} balance
   * @param {number} weightInvestment
   * @param {number} tier
   * @param {ContractTxOptions} options
   *
   * @selector 0x90c3ef3a
   **/
  updateToken: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      balance: bigint,
      weightInvestment: number,
      tier: number,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   * Remove a token from the registry
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0xc964c4ec
   **/
  removeToken: GenericContractTxCall<
    ChainApi,
    (
      tokenId: number,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
