// Generated by dedot cli

import type { AccountId32 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type SharedTokenData = {
  tokenContract: AccountId32;
  oracleContract: AccountId32;
  balance: bigint;
  weightInvestment: number;
  tier: number;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Registry = {
  tokens: { get(arg: number): Promise<SharedTokenData | undefined> };
  nextTokenId: number;
  owner: AccountId32;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "TokenNotFound"
  | "OracleCallFailed"
  | "InvalidParameter"
  | "InsufficientBalance";

export type SharedEnrichedTokenData = {
  tokenContract: AccountId32;
  oracleContract: AccountId32;
  balance: bigint;
  weightInvestment: number;
  tier: number;
  marketCap: bigint;
  marketVolume: bigint;
  price: bigint;
};

export type InkEnvNoChainExtension = null;
