// Generated by dedot cli

import type { AccountId32, AccountId32Like } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type SharedTokenData = {
  tokenContract: AccountId32;
  oracleContract: AccountId32;
  balance: bigint;
  weightInvestment: number;
  tier: number;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type SharedRole =
  | "TokenManager"
  | "TokenUpdater"
  | "EmergencyController";

export type Registry = {
  tokens: { get(arg: number): Promise<SharedTokenData | undefined> };
  tokenContractToId: { get(arg: AccountId32Like): Promise<number | undefined> };
  roleMembers: {
    get(arg: [SharedRole, AccountId32Like]): Promise<boolean | undefined>;
  };
  nextTokenId: number;
  owner: AccountId32;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance";

export type SharedEnrichedTokenData = {
  tokenContract: AccountId32;
  oracleContract: AccountId32;
  balance: bigint;
  weightInvestment: number;
  tier: number;
  marketCap: bigint;
  marketVolume: bigint;
  price: bigint;
};

export type InkEnvNoChainExtension = null;
