// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   * Event emitted when allowance by `owner` to `spender` changes.
   *
   *
   **/
  Approval: GenericContractEvent<
    "Approval",
    {
      /**
       * Account providing allowance.
       *
       * @indexed: true
       **/
      owner: AccountId32;
      /**
       * Allowance beneficiary.
       *
       * @indexed: true
       **/
      spender: AccountId32;
      /**
       * New allowance amount.
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Event emitted when transfer of tokens occurs.
   *
   *
   **/
  Transfer: GenericContractEvent<
    "Transfer",
    {
      /**
       * Transfer sender. `None` in case of minting new tokens.
       *
       * @indexed: true
       **/
      from: AccountId32 | undefined;
      /**
       * Transfer recipient. `None` in case of burning tokens.
       *
       * @indexed: true
       **/
      to: AccountId32 | undefined;
      /**
       * Amount of tokens transferred (or minted/burned).
       *
       * @indexed: false
       **/
      value: bigint;
    },
    Type
  >;
}
