// Generated by dedot cli

import type { H160, AccountId32Like } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Token = {
  data: TokenDataPsp22Data;
  name?: string | undefined;
  symbol?: string | undefined;
  decimals: number;
  owner: H160;
  authorizedMinters: Array<H160>;
  authorizedBurners: Array<H160>;
};

export type TokenDataPsp22Data = {
  totalSupply: bigint;
  balances: { get(arg: AccountId32Like): Promise<bigint | undefined> };
  allowances: {
    get(arg: [AccountId32Like, AccountId32Like]): Promise<bigint | undefined>;
  };
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type TokenErrorsPsp22Error =
  | { type: "Custom"; value: string }
  | { type: "InsufficientBalance" }
  | { type: "InsufficientAllowance" }
  | { type: "ZeroRecipientAddress" }
  | { type: "ZeroSenderAddress" }
  | { type: "SafeTransferCheckFailed"; value: string };
