// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  AccountId32Like,
  Result,
  AccountId32,
  BytesLike,
} from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from "dedot/contracts";
import type { TokenErrorsPsp22Error, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<ChainApi extends GenericSubstrateApi>
  extends GenericContractQuery<ChainApi> {
  /**
   *
   * @param {AccountId32Like} newOwner
   * @param {ContractCallOptions} options
   *
   * @selector 0x107e33ea
   **/
  transferOwnership: GenericContractQueryCall<
    ChainApi,
    (
      newOwner: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<AccountId32, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {AccountId32Like} minter
   * @param {ContractCallOptions} options
   *
   * @selector 0x08a962c8
   **/
  addAuthorizedMinter: GenericContractQueryCall<
    ChainApi,
    (
      minter: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} minter
   * @param {ContractCallOptions} options
   *
   * @selector 0x89da728d
   **/
  removeAuthorizedMinter: GenericContractQueryCall<
    ChainApi,
    (
      minter: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x06dcf43c
   **/
  getAuthorizedMinters: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<AccountId32>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} burner
   * @param {ContractCallOptions} options
   *
   * @selector 0xc2f2347a
   **/
  addAuthorizedBurner: GenericContractQueryCall<
    ChainApi,
    (
      burner: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} burner
   * @param {ContractCallOptions} options
   *
   * @selector 0x13d1b1f6
   **/
  removeAuthorizedBurner: GenericContractQueryCall<
    ChainApi,
    (
      burner: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xabba5de3
   **/
  getAuthorizedBurners: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<AccountId32>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} to
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0x1d2f13c5
   **/
  mintTo: GenericContractQueryCall<
    ChainApi,
    (
      to: AccountId32Like,
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} from
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0x27212bbb
   **/
  burnFrom: GenericContractQueryCall<
    ChainApi,
    (
      from: AccountId32Like,
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x162df8c2
   **/
  psp22TotalSupply: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {AccountId32Like} owner
   * @param {ContractCallOptions} options
   *
   * @selector 0x6568382f
   **/
  psp22BalanceOf: GenericContractQueryCall<
    ChainApi,
    (
      owner: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {AccountId32Like} owner
   * @param {AccountId32Like} spender
   * @param {ContractCallOptions} options
   *
   * @selector 0x4d47d921
   **/
  psp22Allowance: GenericContractQueryCall<
    ChainApi,
    (
      owner: AccountId32Like,
      spender: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {AccountId32Like} to
   * @param {bigint} value
   * @param {BytesLike} data
   * @param {ContractCallOptions} options
   *
   * @selector 0xdb20f9f5
   **/
  psp22Transfer: GenericContractQueryCall<
    ChainApi,
    (
      to: AccountId32Like,
      value: bigint,
      data: BytesLike,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} from
   * @param {AccountId32Like} to
   * @param {bigint} value
   * @param {BytesLike} data
   * @param {ContractCallOptions} options
   *
   * @selector 0x54b3c76e
   **/
  psp22TransferFrom: GenericContractQueryCall<
    ChainApi,
    (
      from: AccountId32Like,
      to: AccountId32Like,
      value: bigint,
      data: BytesLike,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} spender
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0xb20f1bbd
   **/
  psp22Approve: GenericContractQueryCall<
    ChainApi,
    (
      spender: AccountId32Like,
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} spender
   * @param {bigint} deltaValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x96d6b57a
   **/
  psp22IncreaseAllowance: GenericContractQueryCall<
    ChainApi,
    (
      spender: AccountId32Like,
      deltaValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {AccountId32Like} spender
   * @param {bigint} deltaValue
   * @param {ContractCallOptions} options
   *
   * @selector 0xfecb57d5
   **/
  psp22DecreaseAllowance: GenericContractQueryCall<
    ChainApi,
    (
      spender: AccountId32Like,
      deltaValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x3d261bd4
   **/
  psp22MetadataTokenName: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        string | undefined,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x34205be5
   **/
  psp22MetadataTokenSymbol: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        string | undefined,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7271b782
   **/
  psp22MetadataTokenDecimals: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0xfc3c75d4
   **/
  psp22MintableMint: GenericContractQueryCall<
    ChainApi,
    (
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0x7a9da510
   **/
  psp22BurnableBurn: GenericContractQueryCall<
    ChainApi,
    (
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], TokenErrorsPsp22Error>,
        ContractCallResult<ChainApi>
      >
    >
  >;
}
