// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   *
   *
   **/
  SwapExecuted: GenericContractEvent<
    "SwapExecuted",
    {
      /**
       *
       * @indexed: true
       **/
      from: AccountId32;
      /**
       *
       * @indexed: true
       **/
      to: AccountId32;
      /**
       *
       * @indexed: false
       **/
      amountIn: bigint;
      /**
       *
       * @indexed: false
       **/
      amountOut: bigint;
    },
    Type
  >;
}
