// Generated by dedot cli

import type {
  VersionedGenericSubstrateApi,
  RpcVersion,
  RpcV2,
} from "dedot/types";
import type { InkGenericContractApi, WithLazyStorage } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import type { InkPrimitivesLangError, DexHydraDxDex } from "./types.js";
import { ContractQuery } from "./query.js";
import { ContractTx } from "./tx.js";
import { ConstructorQuery } from "./constructor-query.js";
import { ConstructorTx } from "./constructor-tx.js";
import { ContractEvents } from "./events.js";

export * from "./types.js";

/**
 * @name: DexContractApi
 * @contractName: dex
 * @contractVersion: 0.1.0
 * @authors: 3dln <ashcan@3dln.com>
 * @language: ink! 6.0.0-alpha.3
 **/
export interface DexContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<Rv, ChainApi> {
  metadataType: "ink";
  query: ContractQuery<ChainApi[Rv], "ink">;
  tx: ContractTx<ChainApi[Rv], "ink">;
  constructorQuery: ConstructorQuery<ChainApi[Rv], "ink">;
  constructorTx: ConstructorTx<ChainApi[Rv], DexContractApi, "ink">;
  events: ContractEvents<ChainApi[Rv], "ink">;
  storage: {
    root(): Promise<DexHydraDxDex>;
    lazy(): WithLazyStorage<DexHydraDxDex>;
  };

  types: {
    ChainApi: ChainApi[Rv];
    RootStorage: DexHydraDxDex;
    LazyStorage: WithLazyStorage<DexHydraDxDex>;
    LangError: InkPrimitivesLangError;
  };
}
