// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { SharedError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractQuery<ChainApi, Type> {
  /**
   * Admin: Add or update a pool (for demo/testing)
   *
   * @param {H160} tokenA
   * @param {H160} tokenB
   * @param {bigint} reserveA
   * @param {bigint} reserveB
   * @param {ContractCallOptions} options
   *
   * @selector 0xd9942f7b
   **/
  setPool: GenericContractQueryCall<
    ChainApi,
    (
      tokenA: H160,
      tokenB: H160,
      reserveA: bigint,
      reserveB: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Swap tokens from one to another
   *
   * @param {H160} from
   * @param {H160} to
   * @param {bigint} amount
   * @param {Array<H160>} path
   * @param {ContractCallOptions} options
   *
   * @selector 0x0d0e0f10
   **/
  swap: GenericContractQueryCall<
    ChainApi,
    (
      from: H160,
      to: H160,
      amount: bigint,
      path: Array<H160>,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Get token price
   *
   * @param {H160} token
   * @param {ContractCallOptions} options
   *
   * @selector 0x11121314
   **/
  getTokenPrice: GenericContractQueryCall<
    ChainApi,
    (
      token: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, SharedError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;
}
