// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Admin: Add or update a pool (for demo/testing)
   *
   * @param {H160} tokenA
   * @param {H160} tokenB
   * @param {bigint} reserveA
   * @param {bigint} reserveB
   * @param {ContractTxOptions} options
   *
   * @selector 0xd9942f7b
   **/
  setPool: GenericContractTxCall<
    ChainApi,
    (
      tokenA: H160,
      tokenB: H160,
      reserveA: bigint,
      reserveB: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Set default fee for new pools (owner only)
   *
   * @param {number} feeBp
   * @param {ContractTxOptions} options
   *
   * @selector 0xcb642a2e
   **/
  setDefaultFee: GenericContractTxCall<
    ChainApi,
    (
      feeBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Swap tokens with slippage protection
   * Returns error if output is less than min_amount_out
   *
   * @param {H160} from
   * @param {H160} to
   * @param {bigint} amountIn
   * @param {bigint} minAmountOut
   * @param {ContractTxOptions} options
   *
   * @selector 0x36afaae2
   **/
  swapWithSlippage: GenericContractTxCall<
    ChainApi,
    (
      from: H160,
      to: H160,
      amountIn: bigint,
      minAmountOut: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Original swap function (backward compatible)
   *
   * @param {H160} from
   * @param {H160} to
   * @param {bigint} amount
   * @param {Array<H160>} path
   * @param {ContractTxOptions} options
   *
   * @selector 0x0d0e0f10
   **/
  swap: GenericContractTxCall<
    ChainApi,
    (
      from: H160,
      to: H160,
      amount: bigint,
      path: Array<H160>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Add liquidity to a pool
   * Returns LP tokens minted
   *
   * @param {H160} tokenA
   * @param {H160} tokenB
   * @param {bigint} amountA
   * @param {bigint} amountB
   * @param {bigint} minLpTokens
   * @param {ContractTxOptions} options
   *
   * @selector 0x264cd04b
   **/
  addLiquidity: GenericContractTxCall<
    ChainApi,
    (
      tokenA: H160,
      tokenB: H160,
      amountA: bigint,
      amountB: bigint,
      minLpTokens: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Remove liquidity from a pool
   * Returns (amount_a, amount_b) withdrawn
   *
   * @param {H160} tokenA
   * @param {H160} tokenB
   * @param {bigint} lpTokens
   * @param {bigint} minAmountA
   * @param {bigint} minAmountB
   * @param {ContractTxOptions} options
   *
   * @selector 0xbdd16bfa
   **/
  removeLiquidity: GenericContractTxCall<
    ChainApi,
    (
      tokenA: H160,
      tokenB: H160,
      lpTokens: bigint,
      minAmountA: bigint,
      minAmountB: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
