// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Admin: Add or update a pool (for demo/testing)
   *
   * @param {H160} tokenA
   * @param {H160} tokenB
   * @param {bigint} reserveA
   * @param {bigint} reserveB
   * @param {ContractTxOptions} options
   *
   * @selector 0xd9942f7b
   **/
  setPool: GenericContractTxCall<
    ChainApi,
    (
      tokenA: H160,
      tokenB: H160,
      reserveA: bigint,
      reserveB: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Swap tokens from one to another
   *
   * @param {H160} from
   * @param {H160} to
   * @param {bigint} amount
   * @param {Array<H160>} path
   * @param {ContractTxOptions} options
   *
   * @selector 0x0d0e0f10
   **/
  swap: GenericContractTxCall<
    ChainApi,
    (
      from: H160,
      to: H160,
      amount: bigint,
      path: Array<H160>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
