// Generated by dedot cli

import type { H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type DexPool = {
  tokenA: H160;
  tokenB: H160;
  reserveA: bigint;
  reserveB: bigint;
  totalLpTokens: bigint;
  feeBp: number;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type DexLpPosition = {
  lpTokens: bigint;
  initialDepositA: bigint;
  initialDepositB: bigint;
  timestamp: bigint;
};

export type DexHydraDxDex = {
  pools: { get(arg: [H160, H160]): Promise<DexPool | undefined> };
  lpPositions: {
    get(arg: [[H160, H160], H160]): Promise<DexLpPosition | undefined>;
  };
  owner: H160;
  reentrancyGuard: SharedUtilsReentrancyGuard;
  poolKeys: Array<[H160, H160]>;
  defaultFeeBp: number;
};

export type SharedUtilsReentrancyGuard = { executing: boolean };

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance"
  | "ContractPaused"
  | "CrossContractCallFailed"
  | "TransferFailed"
  | "InvalidParameters";
